# Site settings
title: Waterway Life
email: lifewaterway@gmail.com
url: https://waterway.life
description: "A experiential website to deliver the exquisite lifestyle in Punggol area. Amenities, Restaurants, Convenience all at your doorstep."
skills: "NorthEast Living"
meta_author: Ooi Vincent

# Google webmaster tools
google_verify:

# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:

# Contact form:
# - static : pass through formspree.io to validate email sending
# - disqus : replace contact form by disqus thread
# - comment the line below if you want to stick with the default PHP contact form
contact: static

# If you use disqus you need disqus shortname
# https://help.disqus.com/customer/portal/articles/466208
disqus_shortname: waterway

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: 18bc9c #80B3FF
  primary-rgb: "24,288,156" #"128,179,255"
  secondary: 2c3e50 #FD6E8A
  secondary-dark: 233140 #A2122F

# Footer settings
footer:
  copyright: Vincent Ooi
  location: Punggol, Singapore
  social: Join the Chatter
  credits: Credits

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: http://twitter.com/waterwayliving
  - title: facebook
    url: https://www.facebook.com/WaterwayLiving-630101467180596/
  - title: github
    url: http://github.com/waterwaylife

# Postal address (add as many lines as necessary)
address:
  - line: 670A Edgefield Plains
  - line: Singapore 821670

# Credits content
credits: 'Come visit Punggol and experience nature all over again.</a>.'

# Build settings
markdown: kramdown
permalink: pretty
